server:
  port: 8081

spring:
  application:
    name: football-match-intelligence
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    com.ritangkar.footballintel: INFO
